import { readdirSync, statSync, copyFileSync, writeFileSync, existsSync, mkdirSync, rmSync } from "fs";
import { join, relative, extname } from "path";
import { execSync } from "child_process";

const root = join(import.meta.dir, "..");
const frontendDir = join(root, "..", "desktop", "renderer-dist");
const embeddedDir = join(root, ".embedded");
const outputFile = join(root, "generated-assets.ts");

const MIME_TYPES: Record<string, string> = {
  ".html": "text/html",
  ".css": "text/css",
  ".js": "application/javascript",
  ".json": "application/json",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".ico": "image/x-icon",
  ".woff2": "font/woff2",
  ".woff": "font/woff",
  ".txt": "text/plain",
  ".map": "application/json",
};

// Build the frontend if not already built
if (!existsSync(frontendDir)) {
  console.log("Building frontend...");
  execSync("pnpm --filter @git-glance/desktop build", { stdio: "inherit", cwd: root, env: { ...process.env, CI: "true" } });
  if (!existsSync(frontendDir)) {
    console.error(`Frontend dist not found at ${frontendDir} after build`);
    process.exit(1);
  }
} else {
  console.log("Frontend already built, skipping build step");
}

// Clear and repopulate .embedded/
rmSync(embeddedDir, { recursive: true, force: true });
mkdirSync(embeddedDir, { recursive: true });

function collectFiles(dir: string, baseDir: string): string[] {
  const files: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const st = statSync(full);
    if (st.isDirectory()) {
      files.push(...collectFiles(full, baseDir));
    } else {
      files.push(full);
    }
  }
  return files;
}

const allFiles = collectFiles(frontendDir, frontendDir);

// Copy files to .embedded/
for (const filePath of allFiles) {
  const relPath = relative(frontendDir, filePath);
  const dest = join(embeddedDir, relPath);
  mkdirSync(join(dest, ".."), { recursive: true });
  copyFileSync(filePath, dest);
}

// Generate TypeScript file with static import statements
const importStatements: string[] = [];
const mapEntries: string[] = [];

for (const filePath of allFiles) {
  const relPath = relative(frontendDir, filePath);
  const safeName = "f" + relPath.replace(/[^a-zA-Z0-9_]/g, "_");
  const mime = MIME_TYPES[extname(filePath)] || "application/octet-stream";
  importStatements.push(`import ${safeName} from "./.embedded/${relPath}" with { type: "text" };`);
  mapEntries.push(`  ${JSON.stringify(relPath)}: { content: ${safeName}, mimeType: ${JSON.stringify(mime)} }`);
}

const output = `// Auto-generated by scripts/embed-assets.ts — do not edit manually
${importStatements.join("\n")}

export const embeddedAssets: Record<string, { content: string; mimeType: string }> = {
${mapEntries.join(",\n")}
};
`;

writeFileSync(outputFile, output);
console.log(`Copied ${allFiles.length} assets to .embedded/, generated ${outputFile}`);
console.log(`Generated file: ${importStatements.length} imports, ${mapEntries.length} entries`);
