// Auto-generated by scripts/embed-assets.ts — do not edit manually
import fassets_index_BYTtEZg1_js from "./.embedded/assets/index-BYTtEZg1.js" with { type: "text" };
import fassets_abap_Bk27pilz_js from "./.embedded/assets/abap-Bk27pilz.js" with { type: "text" };
import fassets_actionscript_3_CCYDhIKn_js from "./.embedded/assets/actionscript-3-CCYDhIKn.js" with { type: "text" };
import fassets_ada_6USebBQZ_js from "./.embedded/assets/ada-6USebBQZ.js" with { type: "text" };
import fassets_andromeeda_2jUvka7O_js from "./.embedded/assets/andromeeda-2jUvka7O.js" with { type: "text" };
import fassets_angular_html_Cx2mG81s_js from "./.embedded/assets/angular-html-Cx2mG81s.js" with { type: "text" };
import fassets_angular_ts_CTYw4xUY_js from "./.embedded/assets/angular-ts-CTYw4xUY.js" with { type: "text" };
import fassets_apache_DQhGGRJv_js from "./.embedded/assets/apache-DQhGGRJv.js" with { type: "text" };
import fassets_apex_CX_JVEtY_js from "./.embedded/assets/apex-CX_JVEtY.js" with { type: "text" };
import fassets_apl_DfLF7vZE_js from "./.embedded/assets/apl-DfLF7vZE.js" with { type: "text" };
import fassets_applescript_C1FGdl3Q_js from "./.embedded/assets/applescript-C1FGdl3Q.js" with { type: "text" };
import fassets_ara_4cfe67Xs_js from "./.embedded/assets/ara-4cfe67Xs.js" with { type: "text" };
import fassets_asciidoc_0itGI056_js from "./.embedded/assets/asciidoc-0itGI056.js" with { type: "text" };
import fassets_asm_D8PbbEjf_js from "./.embedded/assets/asm-D8PbbEjf.js" with { type: "text" };
import fassets_astro_AB47wpj__js from "./.embedded/assets/astro-AB47wpj-.js" with { type: "text" };
import fassets_aurora_x_Un2qorJz_js from "./.embedded/assets/aurora-x-Un2qorJz.js" with { type: "text" };
import fassets_awk_DSLAuRwH_js from "./.embedded/assets/awk-DSLAuRwH.js" with { type: "text" };
import fassets_ayu_dark_iHKFRVGy_js from "./.embedded/assets/ayu-dark-iHKFRVGy.js" with { type: "text" };
import fassets_ayu_light_BmLeKKx5_js from "./.embedded/assets/ayu-light-BmLeKKx5.js" with { type: "text" };
import fassets_ayu_mirage_Cis3bsjH_js from "./.embedded/assets/ayu-mirage-Cis3bsjH.js" with { type: "text" };
import fassets_ballerina_DxYhAunU_js from "./.embedded/assets/ballerina-DxYhAunU.js" with { type: "text" };
import fassets_bat_B6kxguRH_js from "./.embedded/assets/bat-B6kxguRH.js" with { type: "text" };
import fassets_beancount_BHXBL6wX_js from "./.embedded/assets/beancount-BHXBL6wX.js" with { type: "text" };
import fassets_berry_Cf01C_ce_js from "./.embedded/assets/berry-Cf01C_ce.js" with { type: "text" };
import fassets_bibtex_Bem_ZuEt_js from "./.embedded/assets/bibtex-Bem_ZuEt.js" with { type: "text" };
import fassets_bicep_DrH26wcI_js from "./.embedded/assets/bicep-DrH26wcI.js" with { type: "text" };
import fassets_bird2_96z5qEi6_js from "./.embedded/assets/bird2-96z5qEi6.js" with { type: "text" };
import fassets_blade_CyUo3ThW_js from "./.embedded/assets/blade-CyUo3ThW.js" with { type: "text" };
import fassets_browser_CoaL4hPo_js from "./.embedded/assets/browser-CoaL4hPo.js" with { type: "text" };
import fassets_bsl_llkixvvI_js from "./.embedded/assets/bsl-llkixvvI.js" with { type: "text" };
import fassets_c_M_QHwLJV_js from "./.embedded/assets/c-M_QHwLJV.js" with { type: "text" };
import fassets_c3_DpYJQDnY_js from "./.embedded/assets/c3-DpYJQDnY.js" with { type: "text" };
import fassets_cadence_DB2RyKC9_js from "./.embedded/assets/cadence-DB2RyKC9.js" with { type: "text" };
import fassets_cairo_CGA70EoU_js from "./.embedded/assets/cairo-CGA70EoU.js" with { type: "text" };
import fassets_catppuccin_frappe_CWi4stDP_js from "./.embedded/assets/catppuccin-frappe-CWi4stDP.js" with { type: "text" };
import fassets_catppuccin_latte_Set4i7O1_js from "./.embedded/assets/catppuccin-latte-Set4i7O1.js" with { type: "text" };
import fassets_catppuccin_macchiato_Bt7Xy_eW_js from "./.embedded/assets/catppuccin-macchiato-Bt7Xy_eW.js" with { type: "text" };
import fassets_catppuccin_mocha_Dw5xARNx_js from "./.embedded/assets/catppuccin-mocha-Dw5xARNx.js" with { type: "text" };
import fassets_clarity_BEHOqihr_js from "./.embedded/assets/clarity-BEHOqihr.js" with { type: "text" };
import fassets_clojure_BYS22reK_js from "./.embedded/assets/clojure-BYS22reK.js" with { type: "text" };
import fassets_cmake_YS4EAFvM_js from "./.embedded/assets/cmake-YS4EAFvM.js" with { type: "text" };
import fassets_cobol_D_onAt1P_js from "./.embedded/assets/cobol-D_onAt1P.js" with { type: "text" };
import fassets_codeowners_BjjhOTI__js from "./.embedded/assets/codeowners-BjjhOTI_.js" with { type: "text" };
import fassets_codeql_Bjoj4j9I_js from "./.embedded/assets/codeql-Bjoj4j9I.js" with { type: "text" };
import fassets_coffee_BZHqXyht_js from "./.embedded/assets/coffee-BZHqXyht.js" with { type: "text" };
import fassets_common_lisp_PFwry3X8_js from "./.embedded/assets/common-lisp-PFwry3X8.js" with { type: "text" };
import fassets_coq_DhEteqP__js from "./.embedded/assets/coq-DhEteqP-.js" with { type: "text" };
import fassets_cpp_DTYNR_VD_js from "./.embedded/assets/cpp-DTYNR_VD.js" with { type: "text" };
import fassets_crystal_Dk23maJg_js from "./.embedded/assets/crystal-Dk23maJg.js" with { type: "text" };
import fassets_csharp_CXV_4i9C_js from "./.embedded/assets/csharp-CXV-4i9C.js" with { type: "text" };
import fassets_css_Hrm_FiPm_js from "./.embedded/assets/css-Hrm_FiPm.js" with { type: "text" };
import fassets_csv_Bb2RiIjp_js from "./.embedded/assets/csv-Bb2RiIjp.js" with { type: "text" };
import fassets_cue_jPKgwIWp_js from "./.embedded/assets/cue-jPKgwIWp.js" with { type: "text" };
import fassets_cypher_DVp3L2zk_js from "./.embedded/assets/cypher-DVp3L2zk.js" with { type: "text" };
import fassets_d_2A2RcQU1_js from "./.embedded/assets/d-2A2RcQU1.js" with { type: "text" };
import fassets_dark_plus_BOBE7sFs_js from "./.embedded/assets/dark-plus-BOBE7sFs.js" with { type: "text" };
import fassets_dart_BqtR0KNb_js from "./.embedded/assets/dart-BqtR0KNb.js" with { type: "text" };
import fassets_dax_Dux4VEN0_js from "./.embedded/assets/dax-Dux4VEN0.js" with { type: "text" };
import fassets_desktop_Cc9nitfX_js from "./.embedded/assets/desktop-Cc9nitfX.js" with { type: "text" };
import fassets_diff_B2qZHsnN_js from "./.embedded/assets/diff-B2qZHsnN.js" with { type: "text" };
import fassets_dist_Btmb0PjG_js from "./.embedded/assets/dist-Btmb0PjG.js" with { type: "text" };
import fassets_docker_C_c56wzu_js from "./.embedded/assets/docker-C_c56wzu.js" with { type: "text" };
import fassets_dotenv_BN_qJw2w_js from "./.embedded/assets/dotenv-BN-qJw2w.js" with { type: "text" };
import fassets_dracula_BKRH_oIJ_js from "./.embedded/assets/dracula-BKRH-oIJ.js" with { type: "text" };
import fassets_dracula_soft_M67hNVDZ_js from "./.embedded/assets/dracula-soft-M67hNVDZ.js" with { type: "text" };
import fassets_dream_maker_CumgLPiB_js from "./.embedded/assets/dream-maker-CumgLPiB.js" with { type: "text" };
import fassets_edge_DsaOKcN__js from "./.embedded/assets/edge-DsaOKcN_.js" with { type: "text" };
import fassets_elixir_xhCuhhgU_js from "./.embedded/assets/elixir-xhCuhhgU.js" with { type: "text" };
import fassets_elm_Dx5YNktk_js from "./.embedded/assets/elm-Dx5YNktk.js" with { type: "text" };
import fassets_emacs_lisp_BXCHpRWX_js from "./.embedded/assets/emacs-lisp-BXCHpRWX.js" with { type: "text" };
import fassets_erb_Bvk4dd3S_js from "./.embedded/assets/erb-Bvk4dd3S.js" with { type: "text" };
import fassets_erlang_BES1_Rvb_js from "./.embedded/assets/erlang-BES1_Rvb.js" with { type: "text" };
import fassets_everforest_dark_BAxMHDWs_js from "./.embedded/assets/everforest-dark-BAxMHDWs.js" with { type: "text" };
import fassets_everforest_light_Dlyvv6fn_js from "./.embedded/assets/everforest-light-Dlyvv6fn.js" with { type: "text" };
import fassets_fennel_DvVVnb_7_js from "./.embedded/assets/fennel-DvVVnb_7.js" with { type: "text" };
import fassets_fish_CSIISkcO_js from "./.embedded/assets/fish-CSIISkcO.js" with { type: "text" };
import fassets_fluent_DDOGmJ3P_js from "./.embedded/assets/fluent-DDOGmJ3P.js" with { type: "text" };
import fassets_fortran_fixed_form_BjrnRbg__js from "./.embedded/assets/fortran-fixed-form-BjrnRbg-.js" with { type: "text" };
import fassets_fortran_free_form_DGJBCgQt_js from "./.embedded/assets/fortran-free-form-DGJBCgQt.js" with { type: "text" };
import fassets_fsharp_VSVPuVAq_js from "./.embedded/assets/fsharp-VSVPuVAq.js" with { type: "text" };
import fassets_gdresource_dU2FDiXY_js from "./.embedded/assets/gdresource-dU2FDiXY.js" with { type: "text" };
import fassets_gdscript_CDzG7i3E_js from "./.embedded/assets/gdscript-CDzG7i3E.js" with { type: "text" };
import fassets_gdshader_B9QQu0w5_js from "./.embedded/assets/gdshader-B9QQu0w5.js" with { type: "text" };
import fassets_genie_DKV51Q3L_js from "./.embedded/assets/genie-DKV51Q3L.js" with { type: "text" };
import fassets_gherkin_QlY9Ct92_js from "./.embedded/assets/gherkin-QlY9Ct92.js" with { type: "text" };
import fassets_git_commit_D9ADoGeK_js from "./.embedded/assets/git-commit-D9ADoGeK.js" with { type: "text" };
import fassets_git_rebase_KzZro_K__js from "./.embedded/assets/git-rebase-KzZro_K_.js" with { type: "text" };
import fassets_github_dark_CXtbDx1d_js from "./.embedded/assets/github-dark-CXtbDx1d.js" with { type: "text" };
import fassets_github_dark_default_DxXGqfRT_js from "./.embedded/assets/github-dark-default-DxXGqfRT.js" with { type: "text" };
import fassets_github_dark_dimmed_UXpDxRX9_js from "./.embedded/assets/github-dark-dimmed-UXpDxRX9.js" with { type: "text" };
import fassets_github_dark_high_contrast_CNPaaT7U_js from "./.embedded/assets/github-dark-high-contrast-CNPaaT7U.js" with { type: "text" };
import fassets_github_light_default_Du9_IOLX_js from "./.embedded/assets/github-light-default-Du9-IOLX.js" with { type: "text" };
import fassets_github_light_high_contrast_CwqsIF_h_js from "./.embedded/assets/github-light-high-contrast-CwqsIF-h.js" with { type: "text" };
import fassets_github_light_taCW9qzv_js from "./.embedded/assets/github-light-taCW9qzv.js" with { type: "text" };
import fassets_gleam_DOA6J3Mc_js from "./.embedded/assets/gleam-DOA6J3Mc.js" with { type: "text" };
import fassets_glimmer_js_YX2o31WW_js from "./.embedded/assets/glimmer-js-YX2o31WW.js" with { type: "text" };
import fassets_glimmer_ts_BY0Teo7a_js from "./.embedded/assets/glimmer-ts-BY0Teo7a.js" with { type: "text" };
import fassets_glsl_CBAB8dM0_js from "./.embedded/assets/glsl-CBAB8dM0.js" with { type: "text" };
import fassets_gn_Bu9u24JM_js from "./.embedded/assets/gn-Bu9u24JM.js" with { type: "text" };
import fassets_gnuplot_BuuWufrJ_js from "./.embedded/assets/gnuplot-BuuWufrJ.js" with { type: "text" };
import fassets_go_Dj2taRJV_js from "./.embedded/assets/go-Dj2taRJV.js" with { type: "text" };
import fassets_graphql_CAaQWLYa_js from "./.embedded/assets/graphql-CAaQWLYa.js" with { type: "text" };
import fassets_groovy_CFjM_d7A_js from "./.embedded/assets/groovy-CFjM_d7A.js" with { type: "text" };
import fassets_gruvbox_dark_hard_CxuXTumM_js from "./.embedded/assets/gruvbox-dark-hard-CxuXTumM.js" with { type: "text" };
import fassets_gruvbox_dark_medium_nng_dH79_js from "./.embedded/assets/gruvbox-dark-medium-nng-dH79.js" with { type: "text" };
import fassets_gruvbox_dark_soft_BoA430ZK_js from "./.embedded/assets/gruvbox-dark-soft-BoA430ZK.js" with { type: "text" };
import fassets_gruvbox_light_hard_CjowlOOj_js from "./.embedded/assets/gruvbox-light-hard-CjowlOOj.js" with { type: "text" };
import fassets_gruvbox_light_medium_DcTYU36V_js from "./.embedded/assets/gruvbox-light-medium-DcTYU36V.js" with { type: "text" };
import fassets_gruvbox_light_soft_GTZFJiuL_js from "./.embedded/assets/gruvbox-light-soft-GTZFJiuL.js" with { type: "text" };
import fassets_hack_D1aH5ZnL_js from "./.embedded/assets/hack-D1aH5ZnL.js" with { type: "text" };
import fassets_haml_CaqtuuuD_js from "./.embedded/assets/haml-CaqtuuuD.js" with { type: "text" };
import fassets_handlebars_CDQg3oLm_js from "./.embedded/assets/handlebars-CDQg3oLm.js" with { type: "text" };
import fassets_haskell_CPbZGAdr_js from "./.embedded/assets/haskell-CPbZGAdr.js" with { type: "text" };
import fassets_haxe_h6fcdWSB_js from "./.embedded/assets/haxe-h6fcdWSB.js" with { type: "text" };
import fassets_hcl_CLLOIJ_O_js from "./.embedded/assets/hcl-CLLOIJ-O.js" with { type: "text" };
import fassets_hjson_BGB6IZxI_js from "./.embedded/assets/hjson-BGB6IZxI.js" with { type: "text" };
import fassets_hlsl_BO_BNlZ0_js from "./.embedded/assets/hlsl-BO_BNlZ0.js" with { type: "text" };
import fassets_horizon_BH18_sc5_js from "./.embedded/assets/horizon-BH18-sc5.js" with { type: "text" };
import fassets_horizon_bright_COYM5RGU_js from "./.embedded/assets/horizon-bright-COYM5RGU.js" with { type: "text" };
import fassets_houston_6Fc_wM0K_js from "./.embedded/assets/houston-6Fc_wM0K.js" with { type: "text" };
import fassets_html_I8tqXkKI_js from "./.embedded/assets/html-I8tqXkKI.js" with { type: "text" };
import fassets_html_derivative_CXawk58j_js from "./.embedded/assets/html-derivative-CXawk58j.js" with { type: "text" };
import fassets_http_DLV7I5_4_js from "./.embedded/assets/http-DLV7I5-4.js" with { type: "text" };
import fassets_hurl_DGG4lm7I_js from "./.embedded/assets/hurl-DGG4lm7I.js" with { type: "text" };
import fassets_hxml_Bql02WKv_js from "./.embedded/assets/hxml-Bql02WKv.js" with { type: "text" };
import fassets_hy_5VceCpn4_js from "./.embedded/assets/hy-5VceCpn4.js" with { type: "text" };
import fassets_imba_DzdYcVmj_js from "./.embedded/assets/imba-DzdYcVmj.js" with { type: "text" };
import fassets_ini_DR6P8_20_js from "./.embedded/assets/ini-DR6P8-20.js" with { type: "text" };
import fassets_java_BSTjWUlY_js from "./.embedded/assets/java-BSTjWUlY.js" with { type: "text" };
import fassets_javascript_B4kE_msz_js from "./.embedded/assets/javascript-B4kE_msz.js" with { type: "text" };
import fassets_jinja_UZTfa602_js from "./.embedded/assets/jinja-UZTfa602.js" with { type: "text" };
import fassets_jison_C0jiNnTo_js from "./.embedded/assets/jison-C0jiNnTo.js" with { type: "text" };
import fassets_json_aBhc1vYR_js from "./.embedded/assets/json-aBhc1vYR.js" with { type: "text" };
import fassets_json5_Co2GlfSq_js from "./.embedded/assets/json5-Co2GlfSq.js" with { type: "text" };
import fassets_jsonc_DNkKmZCy_js from "./.embedded/assets/jsonc-DNkKmZCy.js" with { type: "text" };
import fassets_jsonl_BKrZDmtZ_js from "./.embedded/assets/jsonl-BKrZDmtZ.js" with { type: "text" };
import fassets_jsonnet_BqzkC4bB_js from "./.embedded/assets/jsonnet-BqzkC4bB.js" with { type: "text" };
import fassets_jssm_BSm_oxXI_js from "./.embedded/assets/jssm-BSm-oxXI.js" with { type: "text" };
import fassets_jsx_BLCUygjx_js from "./.embedded/assets/jsx-BLCUygjx.js" with { type: "text" };
import fassets_julia_OeRRCIm6_js from "./.embedded/assets/julia-OeRRCIm6.js" with { type: "text" };
import fassets_just_uZq2E_Wz_js from "./.embedded/assets/just-uZq2E_Wz.js" with { type: "text" };
import fassets_kanagawa_dragon_DCwELgEg_js from "./.embedded/assets/kanagawa-dragon-DCwELgEg.js" with { type: "text" };
import fassets_kanagawa_lotus_DeROftmH_js from "./.embedded/assets/kanagawa-lotus-DeROftmH.js" with { type: "text" };
import fassets_kanagawa_wave_D5JNOxwd_js from "./.embedded/assets/kanagawa-wave-D5JNOxwd.js" with { type: "text" };
import fassets_kdl_5l9ZdnsV_js from "./.embedded/assets/kdl-5l9ZdnsV.js" with { type: "text" };
import fassets_kotlin_BnIVd0Zj_js from "./.embedded/assets/kotlin-BnIVd0Zj.js" with { type: "text" };
import fassets_kusto_CjgpuJqI_js from "./.embedded/assets/kusto-CjgpuJqI.js" with { type: "text" };
import fassets_laserwave_B_ORCShN_js from "./.embedded/assets/laserwave-B-ORCShN.js" with { type: "text" };
import fassets_latex_BAWL59bj_js from "./.embedded/assets/latex-BAWL59bj.js" with { type: "text" };
import fassets_lean_Cnb1VkUb_js from "./.embedded/assets/lean-Cnb1VkUb.js" with { type: "text" };
import fassets_less_AwE9O4TL_js from "./.embedded/assets/less-AwE9O4TL.js" with { type: "text" };
import fassets_light_plus_FARtlN37_js from "./.embedded/assets/light-plus-FARtlN37.js" with { type: "text" };
import fassets_liquid_BMkha9f7_js from "./.embedded/assets/liquid-BMkha9f7.js" with { type: "text" };
import fassets_llvm_tJDdt2qd_js from "./.embedded/assets/llvm-tJDdt2qd.js" with { type: "text" };
import fassets_log_D7HFFcnT_js from "./.embedded/assets/log-D7HFFcnT.js" with { type: "text" };
import fassets_logo_C7h1V_Xe_js from "./.embedded/assets/logo-C7h1V_Xe.js" with { type: "text" };
import fassets_lua_bw7zAKym_js from "./.embedded/assets/lua-bw7zAKym.js" with { type: "text" };
import fassets_luau_CQRhZdo1_js from "./.embedded/assets/luau-CQRhZdo1.js" with { type: "text" };
import fassets_make_Dq0XDcoL_js from "./.embedded/assets/make-Dq0XDcoL.js" with { type: "text" };
import fassets_markdown_CIvip5lA_js from "./.embedded/assets/markdown-CIvip5lA.js" with { type: "text" };
import fassets_marko_C5WaTrOH_js from "./.embedded/assets/marko-C5WaTrOH.js" with { type: "text" };
import fassets_material_theme_Cv3_usVE_js from "./.embedded/assets/material-theme-Cv3-usVE.js" with { type: "text" };
import fassets_material_theme_darker_DJONR_dU_js from "./.embedded/assets/material-theme-darker-DJONR-dU.js" with { type: "text" };
import fassets_material_theme_lighter_BbfTYGMy_js from "./.embedded/assets/material-theme-lighter-BbfTYGMy.js" with { type: "text" };
import fassets_material_theme_ocean_BBQrfZko_js from "./.embedded/assets/material-theme-ocean-BBQrfZko.js" with { type: "text" };
import fassets_material_theme_palenight_C_NoBWvS_js from "./.embedded/assets/material-theme-palenight-C-NoBWvS.js" with { type: "text" };
import fassets_matlab_JXc0ggzZ_js from "./.embedded/assets/matlab-JXc0ggzZ.js" with { type: "text" };
import fassets_mdc_Ddc9qnKy_js from "./.embedded/assets/mdc-Ddc9qnKy.js" with { type: "text" };
import fassets_mdx_CoSu4RSl_js from "./.embedded/assets/mdx-CoSu4RSl.js" with { type: "text" };
import fassets_mermaid_C0uHmARS_js from "./.embedded/assets/mermaid-C0uHmARS.js" with { type: "text" };
import fassets_min_dark_5tObRTjc_js from "./.embedded/assets/min-dark-5tObRTjc.js" with { type: "text" };
import fassets_min_light_DXU9ccOp_js from "./.embedded/assets/min-light-DXU9ccOp.js" with { type: "text" };
import fassets_mipsasm_SgFa_Ptq_js from "./.embedded/assets/mipsasm-SgFa_Ptq.js" with { type: "text" };
import fassets_mojo_Co6mmX9t_js from "./.embedded/assets/mojo-Co6mmX9t.js" with { type: "text" };
import fassets_monokai_DwjO0qpF_js from "./.embedded/assets/monokai-DwjO0qpF.js" with { type: "text" };
import fassets_moonbit_Df00Jd4u_js from "./.embedded/assets/moonbit-Df00Jd4u.js" with { type: "text" };
import fassets_move_YRMmZa6E_js from "./.embedded/assets/move-YRMmZa6E.js" with { type: "text" };
import fassets_narrat_CkCLZYPa_js from "./.embedded/assets/narrat-CkCLZYPa.js" with { type: "text" };
import fassets_nextflow_OKvUAqew_js from "./.embedded/assets/nextflow-OKvUAqew.js" with { type: "text" };
import fassets_nextflow_groovy_CvfhV3ho_js from "./.embedded/assets/nextflow-groovy-CvfhV3ho.js" with { type: "text" };
import fassets_nginx_BJrMCqBt_js from "./.embedded/assets/nginx-BJrMCqBt.js" with { type: "text" };
import fassets_night_owl_C6yVJF2Q_js from "./.embedded/assets/night-owl-C6yVJF2Q.js" with { type: "text" };
import fassets_night_owl_light_DIR_h37d_js from "./.embedded/assets/night-owl-light-DIR-h37d.js" with { type: "text" };
import fassets_nim_BgFc4RZx_js from "./.embedded/assets/nim-BgFc4RZx.js" with { type: "text" };
import fassets_nix_yLztInAI_js from "./.embedded/assets/nix-yLztInAI.js" with { type: "text" };
import fassets_nord_D3OhLmlk_js from "./.embedded/assets/nord-D3OhLmlk.js" with { type: "text" };
import fassets_nushell_DCDN70Fn_js from "./.embedded/assets/nushell-DCDN70Fn.js" with { type: "text" };
import fassets_objective_c_DkXt7g53_js from "./.embedded/assets/objective-c-DkXt7g53.js" with { type: "text" };
import fassets_objective_cpp_CkuzR3T2_js from "./.embedded/assets/objective-cpp-CkuzR3T2.js" with { type: "text" };
import fassets_ocaml_Nwfbp7Pq_js from "./.embedded/assets/ocaml-Nwfbp7Pq.js" with { type: "text" };
import fassets_odin_BmjhbgJp_js from "./.embedded/assets/odin-BmjhbgJp.js" with { type: "text" };
import fassets_one_dark_pro_BQwYNK_V_js from "./.embedded/assets/one-dark-pro-BQwYNK-V.js" with { type: "text" };
import fassets_one_light_CBPQwlXK_js from "./.embedded/assets/one-light-CBPQwlXK.js" with { type: "text" };
import fassets_openscad_BDtVw7Ty_js from "./.embedded/assets/openscad-BDtVw7Ty.js" with { type: "text" };
import fassets_pascal_5TJsUumw_js from "./.embedded/assets/pascal-5TJsUumw.js" with { type: "text" };
import fassets_perl_B0mffbOX_js from "./.embedded/assets/perl-B0mffbOX.js" with { type: "text" };
import fassets_php_CgWc8WAz_js from "./.embedded/assets/php-CgWc8WAz.js" with { type: "text" };
import fassets_pierre_dark_6PQ33ae9_js from "./.embedded/assets/pierre-dark-6PQ33ae9.js" with { type: "text" };
import fassets_pierre_dark_soft_xGLibyIB_js from "./.embedded/assets/pierre-dark-soft-xGLibyIB.js" with { type: "text" };
import fassets_pierre_light_fz8Rb3x6_js from "./.embedded/assets/pierre-light-fz8Rb3x6.js" with { type: "text" };
import fassets_pierre_light_soft_J5ozoaoB_js from "./.embedded/assets/pierre-light-soft-J5ozoaoB.js" with { type: "text" };
import fassets_pkl_C7TrO5pd_js from "./.embedded/assets/pkl-C7TrO5pd.js" with { type: "text" };
import fassets_plastic_xlIdlTab_js from "./.embedded/assets/plastic-xlIdlTab.js" with { type: "text" };
import fassets_plsql_DlhFNZ2J_js from "./.embedded/assets/plsql-DlhFNZ2J.js" with { type: "text" };
import fassets_po_BHjDwQBt_js from "./.embedded/assets/po-BHjDwQBt.js" with { type: "text" };
import fassets_poimandres_D86B5bTz_js from "./.embedded/assets/poimandres-D86B5bTz.js" with { type: "text" };
import fassets_polar_O7ZDNW1J_js from "./.embedded/assets/polar-O7ZDNW1J.js" with { type: "text" };
import fassets_postcss_DnUOtnzk_js from "./.embedded/assets/postcss-DnUOtnzk.js" with { type: "text" };
import fassets_powerquery_zOqG_oTR_js from "./.embedded/assets/powerquery-zOqG_oTR.js" with { type: "text" };
import fassets_powershell_CVN40vcI_js from "./.embedded/assets/powershell-CVN40vcI.js" with { type: "text" };
import fassets_prisma_VOBHpSax_js from "./.embedded/assets/prisma-VOBHpSax.js" with { type: "text" };
import fassets_prolog_BYgKtSRc_js from "./.embedded/assets/prolog-BYgKtSRc.js" with { type: "text" };
import fassets_proto_z4Kj2xok_js from "./.embedded/assets/proto-z4Kj2xok.js" with { type: "text" };
import fassets_pug_B1uNnNgD_js from "./.embedded/assets/pug-B1uNnNgD.js" with { type: "text" };
import fassets_puppet_C0BDWzZp_js from "./.embedded/assets/puppet-C0BDWzZp.js" with { type: "text" };
import fassets_purescript_CvZcjKTm_js from "./.embedded/assets/purescript-CvZcjKTm.js" with { type: "text" };
import fassets_python_BQCjNhkc_js from "./.embedded/assets/python-BQCjNhkc.js" with { type: "text" };
import fassets_qml_CYUMfsWf_js from "./.embedded/assets/qml-CYUMfsWf.js" with { type: "text" };
import fassets_qmldir_CsWtzwri_js from "./.embedded/assets/qmldir-CsWtzwri.js" with { type: "text" };
import fassets_qss_CUFcyovH_js from "./.embedded/assets/qss-CUFcyovH.js" with { type: "text" };
import fassets_r_B4WsfLks_js from "./.embedded/assets/r-B4WsfLks.js" with { type: "text" };
import fassets_racket_633rQwcH_js from "./.embedded/assets/racket-633rQwcH.js" with { type: "text" };
import fassets_raku_qCpKeDeU_js from "./.embedded/assets/raku-qCpKeDeU.js" with { type: "text" };
import fassets_razor_QwmzDw44_js from "./.embedded/assets/razor-QwmzDw44.js" with { type: "text" };
import fassets_red_I5fLwuNS_js from "./.embedded/assets/red-I5fLwuNS.js" with { type: "text" };
import fassets_reg_Cd_MGTAG_js from "./.embedded/assets/reg-Cd_MGTAG.js" with { type: "text" };
import fassets_regexp_D5Tl5k0s_js from "./.embedded/assets/regexp-D5Tl5k0s.js" with { type: "text" };
import fassets_rel_BZSOV4AQ_js from "./.embedded/assets/rel-BZSOV4AQ.js" with { type: "text" };
import fassets_resolveThemes_BIArPd7e_js from "./.embedded/assets/resolveThemes-BIArPd7e.js" with { type: "text" };
import fassets_riscv_CDOtroME_js from "./.embedded/assets/riscv-CDOtroME.js" with { type: "text" };
import fassets_rolldown_runtime_S_ySWqyJ_js from "./.embedded/assets/rolldown-runtime-S-ySWqyJ.js" with { type: "text" };
import fassets_ron_BlQXuk7o_js from "./.embedded/assets/ron-BlQXuk7o.js" with { type: "text" };
import fassets_rose_pine_Crsr1Wh6_js from "./.embedded/assets/rose-pine-Crsr1Wh6.js" with { type: "text" };
import fassets_rose_pine_dawn_BseHwNCh_js from "./.embedded/assets/rose-pine-dawn-BseHwNCh.js" with { type: "text" };
import fassets_rose_pine_moon_CTJjJU_f_js from "./.embedded/assets/rose-pine-moon-CTJjJU-f.js" with { type: "text" };
import fassets_rosmsg_CLQxOfnS_js from "./.embedded/assets/rosmsg-CLQxOfnS.js" with { type: "text" };
import fassets_rst_DiM0IcmL_js from "./.embedded/assets/rst-DiM0IcmL.js" with { type: "text" };
import fassets_ruby_Ca34ejXS_js from "./.embedded/assets/ruby-Ca34ejXS.js" with { type: "text" };
import fassets_rust_B4xiChPF_js from "./.embedded/assets/rust-B4xiChPF.js" with { type: "text" };
import fassets_sas_BhJx4Uks_js from "./.embedded/assets/sas-BhJx4Uks.js" with { type: "text" };
import fassets_sass_BS05h_Jl_js from "./.embedded/assets/sass-BS05h-Jl.js" with { type: "text" };
import fassets_scala_BIf3mHPH_js from "./.embedded/assets/scala-BIf3mHPH.js" with { type: "text" };
import fassets_scheme_DvsylDGX_js from "./.embedded/assets/scheme-DvsylDGX.js" with { type: "text" };
import fassets_scss_Ce2Qo8Gf_js from "./.embedded/assets/scss-Ce2Qo8Gf.js" with { type: "text" };
import fassets_sdbl_Mrv_eWjr_js from "./.embedded/assets/sdbl-Mrv_eWjr.js" with { type: "text" };
import fassets_shaderlab_Cs_Irkll_js from "./.embedded/assets/shaderlab-Cs_Irkll.js" with { type: "text" };
import fassets_shellscript_DozCvK4B_js from "./.embedded/assets/shellscript-DozCvK4B.js" with { type: "text" };
import fassets_shellsession_BXwldcoL_js from "./.embedded/assets/shellsession-BXwldcoL.js" with { type: "text" };
import fassets_slack_dark_BayPwCVM_js from "./.embedded/assets/slack-dark-BayPwCVM.js" with { type: "text" };
import fassets_slack_ochin_BHVQSD4w_js from "./.embedded/assets/slack-ochin-BHVQSD4w.js" with { type: "text" };
import fassets_smalltalk_BED3eD5A_js from "./.embedded/assets/smalltalk-BED3eD5A.js" with { type: "text" };
import fassets_snazzy_light_BW8nJzRx_js from "./.embedded/assets/snazzy-light-BW8nJzRx.js" with { type: "text" };
import fassets_solarized_dark_3dkbIcKM_js from "./.embedded/assets/solarized-dark-3dkbIcKM.js" with { type: "text" };
import fassets_solarized_light_D_iKV2_Z_js from "./.embedded/assets/solarized-light-D_iKV2-Z.js" with { type: "text" };
import fassets_solidity_BVVGfP0N_js from "./.embedded/assets/solidity-BVVGfP0N.js" with { type: "text" };
import fassets_soy_DmwtqBuR_js from "./.embedded/assets/soy-DmwtqBuR.js" with { type: "text" };
import fassets_sparql_BoeQIsPp_js from "./.embedded/assets/sparql-BoeQIsPp.js" with { type: "text" };
import fassets_splunk_DD1Id4oM_js from "./.embedded/assets/splunk-DD1Id4oM.js" with { type: "text" };
import fassets_sql_Cypof2eD_js from "./.embedded/assets/sql-Cypof2eD.js" with { type: "text" };
import fassets_ssh_config_BZpz5Zbu_js from "./.embedded/assets/ssh-config-BZpz5Zbu.js" with { type: "text" };
import fassets_stata_B3Lf0U4U_js from "./.embedded/assets/stata-B3Lf0U4U.js" with { type: "text" };
import fassets_stylus_CKAXRXcu_js from "./.embedded/assets/stylus-CKAXRXcu.js" with { type: "text" };
import fassets_surrealql_DQRf_csu_js from "./.embedded/assets/surrealql-DQRf_csu.js" with { type: "text" };
import fassets_svelte_C__bJFdI_js from "./.embedded/assets/svelte-C__bJFdI.js" with { type: "text" };
import fassets_swift_BCyj80_q_js from "./.embedded/assets/swift-BCyj80_q.js" with { type: "text" };
import fassets_synthwave_84_B_ytnfkh_js from "./.embedded/assets/synthwave-84-B-ytnfkh.js" with { type: "text" };
import fassets_system_verilog_C5HS3cra_js from "./.embedded/assets/system-verilog-C5HS3cra.js" with { type: "text" };
import fassets_systemd_DRPd0Zmh_js from "./.embedded/assets/systemd-DRPd0Zmh.js" with { type: "text" };
import fassets_talonscript_lg8ZDojC_js from "./.embedded/assets/talonscript-lg8ZDojC.js" with { type: "text" };
import fassets_tasl_DAlgWgZx_js from "./.embedded/assets/tasl-DAlgWgZx.js" with { type: "text" };
import fassets_tcl_C54zGUr5_js from "./.embedded/assets/tcl-C54zGUr5.js" with { type: "text" };
import fassets_templ_uRSysKhs_js from "./.embedded/assets/templ-uRSysKhs.js" with { type: "text" };
import fassets_terraform_1KUDhoWw_js from "./.embedded/assets/terraform-1KUDhoWw.js" with { type: "text" };
import fassets_tex_BeNhowUU_js from "./.embedded/assets/tex-BeNhowUU.js" with { type: "text" };
import fassets_tokyo_night_CDKf_sdq_js from "./.embedded/assets/tokyo-night-CDKf-sdq.js" with { type: "text" };
import fassets_toml_CnOaI5nq_js from "./.embedded/assets/toml-CnOaI5nq.js" with { type: "text" };
import fassets_ts_tags_D55ioR_5_js from "./.embedded/assets/ts-tags-D55ioR_5.js" with { type: "text" };
import fassets_tsv_D1qT0opZ_js from "./.embedded/assets/tsv-D1qT0opZ.js" with { type: "text" };
import fassets_tsx_DNiIb5Ta_js from "./.embedded/assets/tsx-DNiIb5Ta.js" with { type: "text" };
import fassets_turtle__woyR8bp_js from "./.embedded/assets/turtle-_woyR8bp.js" with { type: "text" };
import fassets_twig_aBRsnEr8_js from "./.embedded/assets/twig-aBRsnEr8.js" with { type: "text" };
import fassets_typescript_BfbhmWdp_js from "./.embedded/assets/typescript-BfbhmWdp.js" with { type: "text" };
import fassets_typespec_Ciho_I39_js from "./.embedded/assets/typespec-Ciho_I39.js" with { type: "text" };
import fassets_typst_BeH_CzsB_js from "./.embedded/assets/typst-BeH_CzsB.js" with { type: "text" };
import fassets_v_L8BEmoEV_js from "./.embedded/assets/v-L8BEmoEV.js" with { type: "text" };
import fassets_vala_CpV9r2Yk_js from "./.embedded/assets/vala-CpV9r2Yk.js" with { type: "text" };
import fassets_vb_dVp5QMmU_js from "./.embedded/assets/vb-dVp5QMmU.js" with { type: "text" };
import fassets_verilog__YjAX56q_js from "./.embedded/assets/verilog-_YjAX56q.js" with { type: "text" };
import fassets_vesper_Dnn_ZQ4I_js from "./.embedded/assets/vesper-Dnn_ZQ4I.js" with { type: "text" };
import fassets_vhdl_A1qFE0Rm_js from "./.embedded/assets/vhdl-A1qFE0Rm.js" with { type: "text" };
import fassets_viml_BMTIznau_js from "./.embedded/assets/viml-BMTIznau.js" with { type: "text" };
import fassets_vitesse_black_CaGwBPUU_js from "./.embedded/assets/vitesse-black-CaGwBPUU.js" with { type: "text" };
import fassets_vitesse_dark_PIVIzvpJ_js from "./.embedded/assets/vitesse-dark-PIVIzvpJ.js" with { type: "text" };
import fassets_vitesse_light_MdjLbxun_js from "./.embedded/assets/vitesse-light-MdjLbxun.js" with { type: "text" };
import fassets_vue_DEhXAKd0_js from "./.embedded/assets/vue-DEhXAKd0.js" with { type: "text" };
import fassets_vue_html_Z4U5FqT8_js from "./.embedded/assets/vue-html-Z4U5FqT8.js" with { type: "text" };
import fassets_vue_vine_Bq6CITKj_js from "./.embedded/assets/vue-vine-Bq6CITKj.js" with { type: "text" };
import fassets_vyper_Bxfbg29p_js from "./.embedded/assets/vyper-Bxfbg29p.js" with { type: "text" };
import fassets_wasm_B6hke7JD_js from "./.embedded/assets/wasm-B6hke7JD.js" with { type: "text" };
import fassets_wasm_Dvakx5c__js from "./.embedded/assets/wasm-Dvakx5c_.js" with { type: "text" };
import fassets_wenyan_CTBBARHG_js from "./.embedded/assets/wenyan-CTBBARHG.js" with { type: "text" };
import fassets_wgsl_C9UXKH_V_js from "./.embedded/assets/wgsl-C9UXKH_V.js" with { type: "text" };
import fassets_wikitext_Bf_Xqod0_js from "./.embedded/assets/wikitext-Bf-Xqod0.js" with { type: "text" };
import fassets_wit_CRykxNoI_js from "./.embedded/assets/wit-CRykxNoI.js" with { type: "text" };
import fassets_wolfram__EBZbNmI_js from "./.embedded/assets/wolfram-_EBZbNmI.js" with { type: "text" };
import fassets_worker_BfT47q8r_js from "./.embedded/assets/worker-BfT47q8r.js" with { type: "text" };
import fassets_worker_I4CdPtO9_js from "./.embedded/assets/worker-I4CdPtO9.js" with { type: "text" };
import fassets_xml_Drv94STt_js from "./.embedded/assets/xml-Drv94STt.js" with { type: "text" };
import fassets_xsl_UGBeos0a_js from "./.embedded/assets/xsl-UGBeos0a.js" with { type: "text" };
import fassets_yaml_BbVzvNDQ_js from "./.embedded/assets/yaml-BbVzvNDQ.js" with { type: "text" };
import fassets_zenscript_De_g7R2L_js from "./.embedded/assets/zenscript-De-g7R2L.js" with { type: "text" };
import fassets_zig_Bzq_RqGF_js from "./.embedded/assets/zig-Bzq_RqGF.js" with { type: "text" };
import fassets_index_B_B5WRu6_css from "./.embedded/assets/index-B-B5WRu6.css" with { type: "text" };
import fassets_worker_UK_TsInR_js from "./.embedded/assets/worker-UK_TsInR.js" with { type: "text" };
import findex_html from "./.embedded/index.html" with { type: "text" };

export const embeddedAssets: Record<string, { content: string; mimeType: string }> = {
  "assets/index-BYTtEZg1.js": { content: fassets_index_BYTtEZg1_js, mimeType: "application/javascript" },
  "assets/abap-Bk27pilz.js": { content: fassets_abap_Bk27pilz_js, mimeType: "application/javascript" },
  "assets/actionscript-3-CCYDhIKn.js": { content: fassets_actionscript_3_CCYDhIKn_js, mimeType: "application/javascript" },
  "assets/ada-6USebBQZ.js": { content: fassets_ada_6USebBQZ_js, mimeType: "application/javascript" },
  "assets/andromeeda-2jUvka7O.js": { content: fassets_andromeeda_2jUvka7O_js, mimeType: "application/javascript" },
  "assets/angular-html-Cx2mG81s.js": { content: fassets_angular_html_Cx2mG81s_js, mimeType: "application/javascript" },
  "assets/angular-ts-CTYw4xUY.js": { content: fassets_angular_ts_CTYw4xUY_js, mimeType: "application/javascript" },
  "assets/apache-DQhGGRJv.js": { content: fassets_apache_DQhGGRJv_js, mimeType: "application/javascript" },
  "assets/apex-CX_JVEtY.js": { content: fassets_apex_CX_JVEtY_js, mimeType: "application/javascript" },
  "assets/apl-DfLF7vZE.js": { content: fassets_apl_DfLF7vZE_js, mimeType: "application/javascript" },
  "assets/applescript-C1FGdl3Q.js": { content: fassets_applescript_C1FGdl3Q_js, mimeType: "application/javascript" },
  "assets/ara-4cfe67Xs.js": { content: fassets_ara_4cfe67Xs_js, mimeType: "application/javascript" },
  "assets/asciidoc-0itGI056.js": { content: fassets_asciidoc_0itGI056_js, mimeType: "application/javascript" },
  "assets/asm-D8PbbEjf.js": { content: fassets_asm_D8PbbEjf_js, mimeType: "application/javascript" },
  "assets/astro-AB47wpj-.js": { content: fassets_astro_AB47wpj__js, mimeType: "application/javascript" },
  "assets/aurora-x-Un2qorJz.js": { content: fassets_aurora_x_Un2qorJz_js, mimeType: "application/javascript" },
  "assets/awk-DSLAuRwH.js": { content: fassets_awk_DSLAuRwH_js, mimeType: "application/javascript" },
  "assets/ayu-dark-iHKFRVGy.js": { content: fassets_ayu_dark_iHKFRVGy_js, mimeType: "application/javascript" },
  "assets/ayu-light-BmLeKKx5.js": { content: fassets_ayu_light_BmLeKKx5_js, mimeType: "application/javascript" },
  "assets/ayu-mirage-Cis3bsjH.js": { content: fassets_ayu_mirage_Cis3bsjH_js, mimeType: "application/javascript" },
  "assets/ballerina-DxYhAunU.js": { content: fassets_ballerina_DxYhAunU_js, mimeType: "application/javascript" },
  "assets/bat-B6kxguRH.js": { content: fassets_bat_B6kxguRH_js, mimeType: "application/javascript" },
  "assets/beancount-BHXBL6wX.js": { content: fassets_beancount_BHXBL6wX_js, mimeType: "application/javascript" },
  "assets/berry-Cf01C_ce.js": { content: fassets_berry_Cf01C_ce_js, mimeType: "application/javascript" },
  "assets/bibtex-Bem_ZuEt.js": { content: fassets_bibtex_Bem_ZuEt_js, mimeType: "application/javascript" },
  "assets/bicep-DrH26wcI.js": { content: fassets_bicep_DrH26wcI_js, mimeType: "application/javascript" },
  "assets/bird2-96z5qEi6.js": { content: fassets_bird2_96z5qEi6_js, mimeType: "application/javascript" },
  "assets/blade-CyUo3ThW.js": { content: fassets_blade_CyUo3ThW_js, mimeType: "application/javascript" },
  "assets/browser-CoaL4hPo.js": { content: fassets_browser_CoaL4hPo_js, mimeType: "application/javascript" },
  "assets/bsl-llkixvvI.js": { content: fassets_bsl_llkixvvI_js, mimeType: "application/javascript" },
  "assets/c-M_QHwLJV.js": { content: fassets_c_M_QHwLJV_js, mimeType: "application/javascript" },
  "assets/c3-DpYJQDnY.js": { content: fassets_c3_DpYJQDnY_js, mimeType: "application/javascript" },
  "assets/cadence-DB2RyKC9.js": { content: fassets_cadence_DB2RyKC9_js, mimeType: "application/javascript" },
  "assets/cairo-CGA70EoU.js": { content: fassets_cairo_CGA70EoU_js, mimeType: "application/javascript" },
  "assets/catppuccin-frappe-CWi4stDP.js": { content: fassets_catppuccin_frappe_CWi4stDP_js, mimeType: "application/javascript" },
  "assets/catppuccin-latte-Set4i7O1.js": { content: fassets_catppuccin_latte_Set4i7O1_js, mimeType: "application/javascript" },
  "assets/catppuccin-macchiato-Bt7Xy_eW.js": { content: fassets_catppuccin_macchiato_Bt7Xy_eW_js, mimeType: "application/javascript" },
  "assets/catppuccin-mocha-Dw5xARNx.js": { content: fassets_catppuccin_mocha_Dw5xARNx_js, mimeType: "application/javascript" },
  "assets/clarity-BEHOqihr.js": { content: fassets_clarity_BEHOqihr_js, mimeType: "application/javascript" },
  "assets/clojure-BYS22reK.js": { content: fassets_clojure_BYS22reK_js, mimeType: "application/javascript" },
  "assets/cmake-YS4EAFvM.js": { content: fassets_cmake_YS4EAFvM_js, mimeType: "application/javascript" },
  "assets/cobol-D_onAt1P.js": { content: fassets_cobol_D_onAt1P_js, mimeType: "application/javascript" },
  "assets/codeowners-BjjhOTI_.js": { content: fassets_codeowners_BjjhOTI__js, mimeType: "application/javascript" },
  "assets/codeql-Bjoj4j9I.js": { content: fassets_codeql_Bjoj4j9I_js, mimeType: "application/javascript" },
  "assets/coffee-BZHqXyht.js": { content: fassets_coffee_BZHqXyht_js, mimeType: "application/javascript" },
  "assets/common-lisp-PFwry3X8.js": { content: fassets_common_lisp_PFwry3X8_js, mimeType: "application/javascript" },
  "assets/coq-DhEteqP-.js": { content: fassets_coq_DhEteqP__js, mimeType: "application/javascript" },
  "assets/cpp-DTYNR_VD.js": { content: fassets_cpp_DTYNR_VD_js, mimeType: "application/javascript" },
  "assets/crystal-Dk23maJg.js": { content: fassets_crystal_Dk23maJg_js, mimeType: "application/javascript" },
  "assets/csharp-CXV-4i9C.js": { content: fassets_csharp_CXV_4i9C_js, mimeType: "application/javascript" },
  "assets/css-Hrm_FiPm.js": { content: fassets_css_Hrm_FiPm_js, mimeType: "application/javascript" },
  "assets/csv-Bb2RiIjp.js": { content: fassets_csv_Bb2RiIjp_js, mimeType: "application/javascript" },
  "assets/cue-jPKgwIWp.js": { content: fassets_cue_jPKgwIWp_js, mimeType: "application/javascript" },
  "assets/cypher-DVp3L2zk.js": { content: fassets_cypher_DVp3L2zk_js, mimeType: "application/javascript" },
  "assets/d-2A2RcQU1.js": { content: fassets_d_2A2RcQU1_js, mimeType: "application/javascript" },
  "assets/dark-plus-BOBE7sFs.js": { content: fassets_dark_plus_BOBE7sFs_js, mimeType: "application/javascript" },
  "assets/dart-BqtR0KNb.js": { content: fassets_dart_BqtR0KNb_js, mimeType: "application/javascript" },
  "assets/dax-Dux4VEN0.js": { content: fassets_dax_Dux4VEN0_js, mimeType: "application/javascript" },
  "assets/desktop-Cc9nitfX.js": { content: fassets_desktop_Cc9nitfX_js, mimeType: "application/javascript" },
  "assets/diff-B2qZHsnN.js": { content: fassets_diff_B2qZHsnN_js, mimeType: "application/javascript" },
  "assets/dist-Btmb0PjG.js": { content: fassets_dist_Btmb0PjG_js, mimeType: "application/javascript" },
  "assets/docker-C_c56wzu.js": { content: fassets_docker_C_c56wzu_js, mimeType: "application/javascript" },
  "assets/dotenv-BN-qJw2w.js": { content: fassets_dotenv_BN_qJw2w_js, mimeType: "application/javascript" },
  "assets/dracula-BKRH-oIJ.js": { content: fassets_dracula_BKRH_oIJ_js, mimeType: "application/javascript" },
  "assets/dracula-soft-M67hNVDZ.js": { content: fassets_dracula_soft_M67hNVDZ_js, mimeType: "application/javascript" },
  "assets/dream-maker-CumgLPiB.js": { content: fassets_dream_maker_CumgLPiB_js, mimeType: "application/javascript" },
  "assets/edge-DsaOKcN_.js": { content: fassets_edge_DsaOKcN__js, mimeType: "application/javascript" },
  "assets/elixir-xhCuhhgU.js": { content: fassets_elixir_xhCuhhgU_js, mimeType: "application/javascript" },
  "assets/elm-Dx5YNktk.js": { content: fassets_elm_Dx5YNktk_js, mimeType: "application/javascript" },
  "assets/emacs-lisp-BXCHpRWX.js": { content: fassets_emacs_lisp_BXCHpRWX_js, mimeType: "application/javascript" },
  "assets/erb-Bvk4dd3S.js": { content: fassets_erb_Bvk4dd3S_js, mimeType: "application/javascript" },
  "assets/erlang-BES1_Rvb.js": { content: fassets_erlang_BES1_Rvb_js, mimeType: "application/javascript" },
  "assets/everforest-dark-BAxMHDWs.js": { content: fassets_everforest_dark_BAxMHDWs_js, mimeType: "application/javascript" },
  "assets/everforest-light-Dlyvv6fn.js": { content: fassets_everforest_light_Dlyvv6fn_js, mimeType: "application/javascript" },
  "assets/fennel-DvVVnb_7.js": { content: fassets_fennel_DvVVnb_7_js, mimeType: "application/javascript" },
  "assets/fish-CSIISkcO.js": { content: fassets_fish_CSIISkcO_js, mimeType: "application/javascript" },
  "assets/fluent-DDOGmJ3P.js": { content: fassets_fluent_DDOGmJ3P_js, mimeType: "application/javascript" },
  "assets/fortran-fixed-form-BjrnRbg-.js": { content: fassets_fortran_fixed_form_BjrnRbg__js, mimeType: "application/javascript" },
  "assets/fortran-free-form-DGJBCgQt.js": { content: fassets_fortran_free_form_DGJBCgQt_js, mimeType: "application/javascript" },
  "assets/fsharp-VSVPuVAq.js": { content: fassets_fsharp_VSVPuVAq_js, mimeType: "application/javascript" },
  "assets/gdresource-dU2FDiXY.js": { content: fassets_gdresource_dU2FDiXY_js, mimeType: "application/javascript" },
  "assets/gdscript-CDzG7i3E.js": { content: fassets_gdscript_CDzG7i3E_js, mimeType: "application/javascript" },
  "assets/gdshader-B9QQu0w5.js": { content: fassets_gdshader_B9QQu0w5_js, mimeType: "application/javascript" },
  "assets/genie-DKV51Q3L.js": { content: fassets_genie_DKV51Q3L_js, mimeType: "application/javascript" },
  "assets/gherkin-QlY9Ct92.js": { content: fassets_gherkin_QlY9Ct92_js, mimeType: "application/javascript" },
  "assets/git-commit-D9ADoGeK.js": { content: fassets_git_commit_D9ADoGeK_js, mimeType: "application/javascript" },
  "assets/git-rebase-KzZro_K_.js": { content: fassets_git_rebase_KzZro_K__js, mimeType: "application/javascript" },
  "assets/github-dark-CXtbDx1d.js": { content: fassets_github_dark_CXtbDx1d_js, mimeType: "application/javascript" },
  "assets/github-dark-default-DxXGqfRT.js": { content: fassets_github_dark_default_DxXGqfRT_js, mimeType: "application/javascript" },
  "assets/github-dark-dimmed-UXpDxRX9.js": { content: fassets_github_dark_dimmed_UXpDxRX9_js, mimeType: "application/javascript" },
  "assets/github-dark-high-contrast-CNPaaT7U.js": { content: fassets_github_dark_high_contrast_CNPaaT7U_js, mimeType: "application/javascript" },
  "assets/github-light-default-Du9-IOLX.js": { content: fassets_github_light_default_Du9_IOLX_js, mimeType: "application/javascript" },
  "assets/github-light-high-contrast-CwqsIF-h.js": { content: fassets_github_light_high_contrast_CwqsIF_h_js, mimeType: "application/javascript" },
  "assets/github-light-taCW9qzv.js": { content: fassets_github_light_taCW9qzv_js, mimeType: "application/javascript" },
  "assets/gleam-DOA6J3Mc.js": { content: fassets_gleam_DOA6J3Mc_js, mimeType: "application/javascript" },
  "assets/glimmer-js-YX2o31WW.js": { content: fassets_glimmer_js_YX2o31WW_js, mimeType: "application/javascript" },
  "assets/glimmer-ts-BY0Teo7a.js": { content: fassets_glimmer_ts_BY0Teo7a_js, mimeType: "application/javascript" },
  "assets/glsl-CBAB8dM0.js": { content: fassets_glsl_CBAB8dM0_js, mimeType: "application/javascript" },
  "assets/gn-Bu9u24JM.js": { content: fassets_gn_Bu9u24JM_js, mimeType: "application/javascript" },
  "assets/gnuplot-BuuWufrJ.js": { content: fassets_gnuplot_BuuWufrJ_js, mimeType: "application/javascript" },
  "assets/go-Dj2taRJV.js": { content: fassets_go_Dj2taRJV_js, mimeType: "application/javascript" },
  "assets/graphql-CAaQWLYa.js": { content: fassets_graphql_CAaQWLYa_js, mimeType: "application/javascript" },
  "assets/groovy-CFjM_d7A.js": { content: fassets_groovy_CFjM_d7A_js, mimeType: "application/javascript" },
  "assets/gruvbox-dark-hard-CxuXTumM.js": { content: fassets_gruvbox_dark_hard_CxuXTumM_js, mimeType: "application/javascript" },
  "assets/gruvbox-dark-medium-nng-dH79.js": { content: fassets_gruvbox_dark_medium_nng_dH79_js, mimeType: "application/javascript" },
  "assets/gruvbox-dark-soft-BoA430ZK.js": { content: fassets_gruvbox_dark_soft_BoA430ZK_js, mimeType: "application/javascript" },
  "assets/gruvbox-light-hard-CjowlOOj.js": { content: fassets_gruvbox_light_hard_CjowlOOj_js, mimeType: "application/javascript" },
  "assets/gruvbox-light-medium-DcTYU36V.js": { content: fassets_gruvbox_light_medium_DcTYU36V_js, mimeType: "application/javascript" },
  "assets/gruvbox-light-soft-GTZFJiuL.js": { content: fassets_gruvbox_light_soft_GTZFJiuL_js, mimeType: "application/javascript" },
  "assets/hack-D1aH5ZnL.js": { content: fassets_hack_D1aH5ZnL_js, mimeType: "application/javascript" },
  "assets/haml-CaqtuuuD.js": { content: fassets_haml_CaqtuuuD_js, mimeType: "application/javascript" },
  "assets/handlebars-CDQg3oLm.js": { content: fassets_handlebars_CDQg3oLm_js, mimeType: "application/javascript" },
  "assets/haskell-CPbZGAdr.js": { content: fassets_haskell_CPbZGAdr_js, mimeType: "application/javascript" },
  "assets/haxe-h6fcdWSB.js": { content: fassets_haxe_h6fcdWSB_js, mimeType: "application/javascript" },
  "assets/hcl-CLLOIJ-O.js": { content: fassets_hcl_CLLOIJ_O_js, mimeType: "application/javascript" },
  "assets/hjson-BGB6IZxI.js": { content: fassets_hjson_BGB6IZxI_js, mimeType: "application/javascript" },
  "assets/hlsl-BO_BNlZ0.js": { content: fassets_hlsl_BO_BNlZ0_js, mimeType: "application/javascript" },
  "assets/horizon-BH18-sc5.js": { content: fassets_horizon_BH18_sc5_js, mimeType: "application/javascript" },
  "assets/horizon-bright-COYM5RGU.js": { content: fassets_horizon_bright_COYM5RGU_js, mimeType: "application/javascript" },
  "assets/houston-6Fc_wM0K.js": { content: fassets_houston_6Fc_wM0K_js, mimeType: "application/javascript" },
  "assets/html-I8tqXkKI.js": { content: fassets_html_I8tqXkKI_js, mimeType: "application/javascript" },
  "assets/html-derivative-CXawk58j.js": { content: fassets_html_derivative_CXawk58j_js, mimeType: "application/javascript" },
  "assets/http-DLV7I5-4.js": { content: fassets_http_DLV7I5_4_js, mimeType: "application/javascript" },
  "assets/hurl-DGG4lm7I.js": { content: fassets_hurl_DGG4lm7I_js, mimeType: "application/javascript" },
  "assets/hxml-Bql02WKv.js": { content: fassets_hxml_Bql02WKv_js, mimeType: "application/javascript" },
  "assets/hy-5VceCpn4.js": { content: fassets_hy_5VceCpn4_js, mimeType: "application/javascript" },
  "assets/imba-DzdYcVmj.js": { content: fassets_imba_DzdYcVmj_js, mimeType: "application/javascript" },
  "assets/ini-DR6P8-20.js": { content: fassets_ini_DR6P8_20_js, mimeType: "application/javascript" },
  "assets/java-BSTjWUlY.js": { content: fassets_java_BSTjWUlY_js, mimeType: "application/javascript" },
  "assets/javascript-B4kE_msz.js": { content: fassets_javascript_B4kE_msz_js, mimeType: "application/javascript" },
  "assets/jinja-UZTfa602.js": { content: fassets_jinja_UZTfa602_js, mimeType: "application/javascript" },
  "assets/jison-C0jiNnTo.js": { content: fassets_jison_C0jiNnTo_js, mimeType: "application/javascript" },
  "assets/json-aBhc1vYR.js": { content: fassets_json_aBhc1vYR_js, mimeType: "application/javascript" },
  "assets/json5-Co2GlfSq.js": { content: fassets_json5_Co2GlfSq_js, mimeType: "application/javascript" },
  "assets/jsonc-DNkKmZCy.js": { content: fassets_jsonc_DNkKmZCy_js, mimeType: "application/javascript" },
  "assets/jsonl-BKrZDmtZ.js": { content: fassets_jsonl_BKrZDmtZ_js, mimeType: "application/javascript" },
  "assets/jsonnet-BqzkC4bB.js": { content: fassets_jsonnet_BqzkC4bB_js, mimeType: "application/javascript" },
  "assets/jssm-BSm-oxXI.js": { content: fassets_jssm_BSm_oxXI_js, mimeType: "application/javascript" },
  "assets/jsx-BLCUygjx.js": { content: fassets_jsx_BLCUygjx_js, mimeType: "application/javascript" },
  "assets/julia-OeRRCIm6.js": { content: fassets_julia_OeRRCIm6_js, mimeType: "application/javascript" },
  "assets/just-uZq2E_Wz.js": { content: fassets_just_uZq2E_Wz_js, mimeType: "application/javascript" },
  "assets/kanagawa-dragon-DCwELgEg.js": { content: fassets_kanagawa_dragon_DCwELgEg_js, mimeType: "application/javascript" },
  "assets/kanagawa-lotus-DeROftmH.js": { content: fassets_kanagawa_lotus_DeROftmH_js, mimeType: "application/javascript" },
  "assets/kanagawa-wave-D5JNOxwd.js": { content: fassets_kanagawa_wave_D5JNOxwd_js, mimeType: "application/javascript" },
  "assets/kdl-5l9ZdnsV.js": { content: fassets_kdl_5l9ZdnsV_js, mimeType: "application/javascript" },
  "assets/kotlin-BnIVd0Zj.js": { content: fassets_kotlin_BnIVd0Zj_js, mimeType: "application/javascript" },
  "assets/kusto-CjgpuJqI.js": { content: fassets_kusto_CjgpuJqI_js, mimeType: "application/javascript" },
  "assets/laserwave-B-ORCShN.js": { content: fassets_laserwave_B_ORCShN_js, mimeType: "application/javascript" },
  "assets/latex-BAWL59bj.js": { content: fassets_latex_BAWL59bj_js, mimeType: "application/javascript" },
  "assets/lean-Cnb1VkUb.js": { content: fassets_lean_Cnb1VkUb_js, mimeType: "application/javascript" },
  "assets/less-AwE9O4TL.js": { content: fassets_less_AwE9O4TL_js, mimeType: "application/javascript" },
  "assets/light-plus-FARtlN37.js": { content: fassets_light_plus_FARtlN37_js, mimeType: "application/javascript" },
  "assets/liquid-BMkha9f7.js": { content: fassets_liquid_BMkha9f7_js, mimeType: "application/javascript" },
  "assets/llvm-tJDdt2qd.js": { content: fassets_llvm_tJDdt2qd_js, mimeType: "application/javascript" },
  "assets/log-D7HFFcnT.js": { content: fassets_log_D7HFFcnT_js, mimeType: "application/javascript" },
  "assets/logo-C7h1V_Xe.js": { content: fassets_logo_C7h1V_Xe_js, mimeType: "application/javascript" },
  "assets/lua-bw7zAKym.js": { content: fassets_lua_bw7zAKym_js, mimeType: "application/javascript" },
  "assets/luau-CQRhZdo1.js": { content: fassets_luau_CQRhZdo1_js, mimeType: "application/javascript" },
  "assets/make-Dq0XDcoL.js": { content: fassets_make_Dq0XDcoL_js, mimeType: "application/javascript" },
  "assets/markdown-CIvip5lA.js": { content: fassets_markdown_CIvip5lA_js, mimeType: "application/javascript" },
  "assets/marko-C5WaTrOH.js": { content: fassets_marko_C5WaTrOH_js, mimeType: "application/javascript" },
  "assets/material-theme-Cv3-usVE.js": { content: fassets_material_theme_Cv3_usVE_js, mimeType: "application/javascript" },
  "assets/material-theme-darker-DJONR-dU.js": { content: fassets_material_theme_darker_DJONR_dU_js, mimeType: "application/javascript" },
  "assets/material-theme-lighter-BbfTYGMy.js": { content: fassets_material_theme_lighter_BbfTYGMy_js, mimeType: "application/javascript" },
  "assets/material-theme-ocean-BBQrfZko.js": { content: fassets_material_theme_ocean_BBQrfZko_js, mimeType: "application/javascript" },
  "assets/material-theme-palenight-C-NoBWvS.js": { content: fassets_material_theme_palenight_C_NoBWvS_js, mimeType: "application/javascript" },
  "assets/matlab-JXc0ggzZ.js": { content: fassets_matlab_JXc0ggzZ_js, mimeType: "application/javascript" },
  "assets/mdc-Ddc9qnKy.js": { content: fassets_mdc_Ddc9qnKy_js, mimeType: "application/javascript" },
  "assets/mdx-CoSu4RSl.js": { content: fassets_mdx_CoSu4RSl_js, mimeType: "application/javascript" },
  "assets/mermaid-C0uHmARS.js": { content: fassets_mermaid_C0uHmARS_js, mimeType: "application/javascript" },
  "assets/min-dark-5tObRTjc.js": { content: fassets_min_dark_5tObRTjc_js, mimeType: "application/javascript" },
  "assets/min-light-DXU9ccOp.js": { content: fassets_min_light_DXU9ccOp_js, mimeType: "application/javascript" },
  "assets/mipsasm-SgFa_Ptq.js": { content: fassets_mipsasm_SgFa_Ptq_js, mimeType: "application/javascript" },
  "assets/mojo-Co6mmX9t.js": { content: fassets_mojo_Co6mmX9t_js, mimeType: "application/javascript" },
  "assets/monokai-DwjO0qpF.js": { content: fassets_monokai_DwjO0qpF_js, mimeType: "application/javascript" },
  "assets/moonbit-Df00Jd4u.js": { content: fassets_moonbit_Df00Jd4u_js, mimeType: "application/javascript" },
  "assets/move-YRMmZa6E.js": { content: fassets_move_YRMmZa6E_js, mimeType: "application/javascript" },
  "assets/narrat-CkCLZYPa.js": { content: fassets_narrat_CkCLZYPa_js, mimeType: "application/javascript" },
  "assets/nextflow-OKvUAqew.js": { content: fassets_nextflow_OKvUAqew_js, mimeType: "application/javascript" },
  "assets/nextflow-groovy-CvfhV3ho.js": { content: fassets_nextflow_groovy_CvfhV3ho_js, mimeType: "application/javascript" },
  "assets/nginx-BJrMCqBt.js": { content: fassets_nginx_BJrMCqBt_js, mimeType: "application/javascript" },
  "assets/night-owl-C6yVJF2Q.js": { content: fassets_night_owl_C6yVJF2Q_js, mimeType: "application/javascript" },
  "assets/night-owl-light-DIR-h37d.js": { content: fassets_night_owl_light_DIR_h37d_js, mimeType: "application/javascript" },
  "assets/nim-BgFc4RZx.js": { content: fassets_nim_BgFc4RZx_js, mimeType: "application/javascript" },
  "assets/nix-yLztInAI.js": { content: fassets_nix_yLztInAI_js, mimeType: "application/javascript" },
  "assets/nord-D3OhLmlk.js": { content: fassets_nord_D3OhLmlk_js, mimeType: "application/javascript" },
  "assets/nushell-DCDN70Fn.js": { content: fassets_nushell_DCDN70Fn_js, mimeType: "application/javascript" },
  "assets/objective-c-DkXt7g53.js": { content: fassets_objective_c_DkXt7g53_js, mimeType: "application/javascript" },
  "assets/objective-cpp-CkuzR3T2.js": { content: fassets_objective_cpp_CkuzR3T2_js, mimeType: "application/javascript" },
  "assets/ocaml-Nwfbp7Pq.js": { content: fassets_ocaml_Nwfbp7Pq_js, mimeType: "application/javascript" },
  "assets/odin-BmjhbgJp.js": { content: fassets_odin_BmjhbgJp_js, mimeType: "application/javascript" },
  "assets/one-dark-pro-BQwYNK-V.js": { content: fassets_one_dark_pro_BQwYNK_V_js, mimeType: "application/javascript" },
  "assets/one-light-CBPQwlXK.js": { content: fassets_one_light_CBPQwlXK_js, mimeType: "application/javascript" },
  "assets/openscad-BDtVw7Ty.js": { content: fassets_openscad_BDtVw7Ty_js, mimeType: "application/javascript" },
  "assets/pascal-5TJsUumw.js": { content: fassets_pascal_5TJsUumw_js, mimeType: "application/javascript" },
  "assets/perl-B0mffbOX.js": { content: fassets_perl_B0mffbOX_js, mimeType: "application/javascript" },
  "assets/php-CgWc8WAz.js": { content: fassets_php_CgWc8WAz_js, mimeType: "application/javascript" },
  "assets/pierre-dark-6PQ33ae9.js": { content: fassets_pierre_dark_6PQ33ae9_js, mimeType: "application/javascript" },
  "assets/pierre-dark-soft-xGLibyIB.js": { content: fassets_pierre_dark_soft_xGLibyIB_js, mimeType: "application/javascript" },
  "assets/pierre-light-fz8Rb3x6.js": { content: fassets_pierre_light_fz8Rb3x6_js, mimeType: "application/javascript" },
  "assets/pierre-light-soft-J5ozoaoB.js": { content: fassets_pierre_light_soft_J5ozoaoB_js, mimeType: "application/javascript" },
  "assets/pkl-C7TrO5pd.js": { content: fassets_pkl_C7TrO5pd_js, mimeType: "application/javascript" },
  "assets/plastic-xlIdlTab.js": { content: fassets_plastic_xlIdlTab_js, mimeType: "application/javascript" },
  "assets/plsql-DlhFNZ2J.js": { content: fassets_plsql_DlhFNZ2J_js, mimeType: "application/javascript" },
  "assets/po-BHjDwQBt.js": { content: fassets_po_BHjDwQBt_js, mimeType: "application/javascript" },
  "assets/poimandres-D86B5bTz.js": { content: fassets_poimandres_D86B5bTz_js, mimeType: "application/javascript" },
  "assets/polar-O7ZDNW1J.js": { content: fassets_polar_O7ZDNW1J_js, mimeType: "application/javascript" },
  "assets/postcss-DnUOtnzk.js": { content: fassets_postcss_DnUOtnzk_js, mimeType: "application/javascript" },
  "assets/powerquery-zOqG_oTR.js": { content: fassets_powerquery_zOqG_oTR_js, mimeType: "application/javascript" },
  "assets/powershell-CVN40vcI.js": { content: fassets_powershell_CVN40vcI_js, mimeType: "application/javascript" },
  "assets/prisma-VOBHpSax.js": { content: fassets_prisma_VOBHpSax_js, mimeType: "application/javascript" },
  "assets/prolog-BYgKtSRc.js": { content: fassets_prolog_BYgKtSRc_js, mimeType: "application/javascript" },
  "assets/proto-z4Kj2xok.js": { content: fassets_proto_z4Kj2xok_js, mimeType: "application/javascript" },
  "assets/pug-B1uNnNgD.js": { content: fassets_pug_B1uNnNgD_js, mimeType: "application/javascript" },
  "assets/puppet-C0BDWzZp.js": { content: fassets_puppet_C0BDWzZp_js, mimeType: "application/javascript" },
  "assets/purescript-CvZcjKTm.js": { content: fassets_purescript_CvZcjKTm_js, mimeType: "application/javascript" },
  "assets/python-BQCjNhkc.js": { content: fassets_python_BQCjNhkc_js, mimeType: "application/javascript" },
  "assets/qml-CYUMfsWf.js": { content: fassets_qml_CYUMfsWf_js, mimeType: "application/javascript" },
  "assets/qmldir-CsWtzwri.js": { content: fassets_qmldir_CsWtzwri_js, mimeType: "application/javascript" },
  "assets/qss-CUFcyovH.js": { content: fassets_qss_CUFcyovH_js, mimeType: "application/javascript" },
  "assets/r-B4WsfLks.js": { content: fassets_r_B4WsfLks_js, mimeType: "application/javascript" },
  "assets/racket-633rQwcH.js": { content: fassets_racket_633rQwcH_js, mimeType: "application/javascript" },
  "assets/raku-qCpKeDeU.js": { content: fassets_raku_qCpKeDeU_js, mimeType: "application/javascript" },
  "assets/razor-QwmzDw44.js": { content: fassets_razor_QwmzDw44_js, mimeType: "application/javascript" },
  "assets/red-I5fLwuNS.js": { content: fassets_red_I5fLwuNS_js, mimeType: "application/javascript" },
  "assets/reg-Cd_MGTAG.js": { content: fassets_reg_Cd_MGTAG_js, mimeType: "application/javascript" },
  "assets/regexp-D5Tl5k0s.js": { content: fassets_regexp_D5Tl5k0s_js, mimeType: "application/javascript" },
  "assets/rel-BZSOV4AQ.js": { content: fassets_rel_BZSOV4AQ_js, mimeType: "application/javascript" },
  "assets/resolveThemes-BIArPd7e.js": { content: fassets_resolveThemes_BIArPd7e_js, mimeType: "application/javascript" },
  "assets/riscv-CDOtroME.js": { content: fassets_riscv_CDOtroME_js, mimeType: "application/javascript" },
  "assets/rolldown-runtime-S-ySWqyJ.js": { content: fassets_rolldown_runtime_S_ySWqyJ_js, mimeType: "application/javascript" },
  "assets/ron-BlQXuk7o.js": { content: fassets_ron_BlQXuk7o_js, mimeType: "application/javascript" },
  "assets/rose-pine-Crsr1Wh6.js": { content: fassets_rose_pine_Crsr1Wh6_js, mimeType: "application/javascript" },
  "assets/rose-pine-dawn-BseHwNCh.js": { content: fassets_rose_pine_dawn_BseHwNCh_js, mimeType: "application/javascript" },
  "assets/rose-pine-moon-CTJjJU-f.js": { content: fassets_rose_pine_moon_CTJjJU_f_js, mimeType: "application/javascript" },
  "assets/rosmsg-CLQxOfnS.js": { content: fassets_rosmsg_CLQxOfnS_js, mimeType: "application/javascript" },
  "assets/rst-DiM0IcmL.js": { content: fassets_rst_DiM0IcmL_js, mimeType: "application/javascript" },
  "assets/ruby-Ca34ejXS.js": { content: fassets_ruby_Ca34ejXS_js, mimeType: "application/javascript" },
  "assets/rust-B4xiChPF.js": { content: fassets_rust_B4xiChPF_js, mimeType: "application/javascript" },
  "assets/sas-BhJx4Uks.js": { content: fassets_sas_BhJx4Uks_js, mimeType: "application/javascript" },
  "assets/sass-BS05h-Jl.js": { content: fassets_sass_BS05h_Jl_js, mimeType: "application/javascript" },
  "assets/scala-BIf3mHPH.js": { content: fassets_scala_BIf3mHPH_js, mimeType: "application/javascript" },
  "assets/scheme-DvsylDGX.js": { content: fassets_scheme_DvsylDGX_js, mimeType: "application/javascript" },
  "assets/scss-Ce2Qo8Gf.js": { content: fassets_scss_Ce2Qo8Gf_js, mimeType: "application/javascript" },
  "assets/sdbl-Mrv_eWjr.js": { content: fassets_sdbl_Mrv_eWjr_js, mimeType: "application/javascript" },
  "assets/shaderlab-Cs_Irkll.js": { content: fassets_shaderlab_Cs_Irkll_js, mimeType: "application/javascript" },
  "assets/shellscript-DozCvK4B.js": { content: fassets_shellscript_DozCvK4B_js, mimeType: "application/javascript" },
  "assets/shellsession-BXwldcoL.js": { content: fassets_shellsession_BXwldcoL_js, mimeType: "application/javascript" },
  "assets/slack-dark-BayPwCVM.js": { content: fassets_slack_dark_BayPwCVM_js, mimeType: "application/javascript" },
  "assets/slack-ochin-BHVQSD4w.js": { content: fassets_slack_ochin_BHVQSD4w_js, mimeType: "application/javascript" },
  "assets/smalltalk-BED3eD5A.js": { content: fassets_smalltalk_BED3eD5A_js, mimeType: "application/javascript" },
  "assets/snazzy-light-BW8nJzRx.js": { content: fassets_snazzy_light_BW8nJzRx_js, mimeType: "application/javascript" },
  "assets/solarized-dark-3dkbIcKM.js": { content: fassets_solarized_dark_3dkbIcKM_js, mimeType: "application/javascript" },
  "assets/solarized-light-D_iKV2-Z.js": { content: fassets_solarized_light_D_iKV2_Z_js, mimeType: "application/javascript" },
  "assets/solidity-BVVGfP0N.js": { content: fassets_solidity_BVVGfP0N_js, mimeType: "application/javascript" },
  "assets/soy-DmwtqBuR.js": { content: fassets_soy_DmwtqBuR_js, mimeType: "application/javascript" },
  "assets/sparql-BoeQIsPp.js": { content: fassets_sparql_BoeQIsPp_js, mimeType: "application/javascript" },
  "assets/splunk-DD1Id4oM.js": { content: fassets_splunk_DD1Id4oM_js, mimeType: "application/javascript" },
  "assets/sql-Cypof2eD.js": { content: fassets_sql_Cypof2eD_js, mimeType: "application/javascript" },
  "assets/ssh-config-BZpz5Zbu.js": { content: fassets_ssh_config_BZpz5Zbu_js, mimeType: "application/javascript" },
  "assets/stata-B3Lf0U4U.js": { content: fassets_stata_B3Lf0U4U_js, mimeType: "application/javascript" },
  "assets/stylus-CKAXRXcu.js": { content: fassets_stylus_CKAXRXcu_js, mimeType: "application/javascript" },
  "assets/surrealql-DQRf_csu.js": { content: fassets_surrealql_DQRf_csu_js, mimeType: "application/javascript" },
  "assets/svelte-C__bJFdI.js": { content: fassets_svelte_C__bJFdI_js, mimeType: "application/javascript" },
  "assets/swift-BCyj80_q.js": { content: fassets_swift_BCyj80_q_js, mimeType: "application/javascript" },
  "assets/synthwave-84-B-ytnfkh.js": { content: fassets_synthwave_84_B_ytnfkh_js, mimeType: "application/javascript" },
  "assets/system-verilog-C5HS3cra.js": { content: fassets_system_verilog_C5HS3cra_js, mimeType: "application/javascript" },
  "assets/systemd-DRPd0Zmh.js": { content: fassets_systemd_DRPd0Zmh_js, mimeType: "application/javascript" },
  "assets/talonscript-lg8ZDojC.js": { content: fassets_talonscript_lg8ZDojC_js, mimeType: "application/javascript" },
  "assets/tasl-DAlgWgZx.js": { content: fassets_tasl_DAlgWgZx_js, mimeType: "application/javascript" },
  "assets/tcl-C54zGUr5.js": { content: fassets_tcl_C54zGUr5_js, mimeType: "application/javascript" },
  "assets/templ-uRSysKhs.js": { content: fassets_templ_uRSysKhs_js, mimeType: "application/javascript" },
  "assets/terraform-1KUDhoWw.js": { content: fassets_terraform_1KUDhoWw_js, mimeType: "application/javascript" },
  "assets/tex-BeNhowUU.js": { content: fassets_tex_BeNhowUU_js, mimeType: "application/javascript" },
  "assets/tokyo-night-CDKf-sdq.js": { content: fassets_tokyo_night_CDKf_sdq_js, mimeType: "application/javascript" },
  "assets/toml-CnOaI5nq.js": { content: fassets_toml_CnOaI5nq_js, mimeType: "application/javascript" },
  "assets/ts-tags-D55ioR_5.js": { content: fassets_ts_tags_D55ioR_5_js, mimeType: "application/javascript" },
  "assets/tsv-D1qT0opZ.js": { content: fassets_tsv_D1qT0opZ_js, mimeType: "application/javascript" },
  "assets/tsx-DNiIb5Ta.js": { content: fassets_tsx_DNiIb5Ta_js, mimeType: "application/javascript" },
  "assets/turtle-_woyR8bp.js": { content: fassets_turtle__woyR8bp_js, mimeType: "application/javascript" },
  "assets/twig-aBRsnEr8.js": { content: fassets_twig_aBRsnEr8_js, mimeType: "application/javascript" },
  "assets/typescript-BfbhmWdp.js": { content: fassets_typescript_BfbhmWdp_js, mimeType: "application/javascript" },
  "assets/typespec-Ciho_I39.js": { content: fassets_typespec_Ciho_I39_js, mimeType: "application/javascript" },
  "assets/typst-BeH_CzsB.js": { content: fassets_typst_BeH_CzsB_js, mimeType: "application/javascript" },
  "assets/v-L8BEmoEV.js": { content: fassets_v_L8BEmoEV_js, mimeType: "application/javascript" },
  "assets/vala-CpV9r2Yk.js": { content: fassets_vala_CpV9r2Yk_js, mimeType: "application/javascript" },
  "assets/vb-dVp5QMmU.js": { content: fassets_vb_dVp5QMmU_js, mimeType: "application/javascript" },
  "assets/verilog-_YjAX56q.js": { content: fassets_verilog__YjAX56q_js, mimeType: "application/javascript" },
  "assets/vesper-Dnn_ZQ4I.js": { content: fassets_vesper_Dnn_ZQ4I_js, mimeType: "application/javascript" },
  "assets/vhdl-A1qFE0Rm.js": { content: fassets_vhdl_A1qFE0Rm_js, mimeType: "application/javascript" },
  "assets/viml-BMTIznau.js": { content: fassets_viml_BMTIznau_js, mimeType: "application/javascript" },
  "assets/vitesse-black-CaGwBPUU.js": { content: fassets_vitesse_black_CaGwBPUU_js, mimeType: "application/javascript" },
  "assets/vitesse-dark-PIVIzvpJ.js": { content: fassets_vitesse_dark_PIVIzvpJ_js, mimeType: "application/javascript" },
  "assets/vitesse-light-MdjLbxun.js": { content: fassets_vitesse_light_MdjLbxun_js, mimeType: "application/javascript" },
  "assets/vue-DEhXAKd0.js": { content: fassets_vue_DEhXAKd0_js, mimeType: "application/javascript" },
  "assets/vue-html-Z4U5FqT8.js": { content: fassets_vue_html_Z4U5FqT8_js, mimeType: "application/javascript" },
  "assets/vue-vine-Bq6CITKj.js": { content: fassets_vue_vine_Bq6CITKj_js, mimeType: "application/javascript" },
  "assets/vyper-Bxfbg29p.js": { content: fassets_vyper_Bxfbg29p_js, mimeType: "application/javascript" },
  "assets/wasm-B6hke7JD.js": { content: fassets_wasm_B6hke7JD_js, mimeType: "application/javascript" },
  "assets/wasm-Dvakx5c_.js": { content: fassets_wasm_Dvakx5c__js, mimeType: "application/javascript" },
  "assets/wenyan-CTBBARHG.js": { content: fassets_wenyan_CTBBARHG_js, mimeType: "application/javascript" },
  "assets/wgsl-C9UXKH_V.js": { content: fassets_wgsl_C9UXKH_V_js, mimeType: "application/javascript" },
  "assets/wikitext-Bf-Xqod0.js": { content: fassets_wikitext_Bf_Xqod0_js, mimeType: "application/javascript" },
  "assets/wit-CRykxNoI.js": { content: fassets_wit_CRykxNoI_js, mimeType: "application/javascript" },
  "assets/wolfram-_EBZbNmI.js": { content: fassets_wolfram__EBZbNmI_js, mimeType: "application/javascript" },
  "assets/worker-BfT47q8r.js": { content: fassets_worker_BfT47q8r_js, mimeType: "application/javascript" },
  "assets/worker-I4CdPtO9.js": { content: fassets_worker_I4CdPtO9_js, mimeType: "application/javascript" },
  "assets/xml-Drv94STt.js": { content: fassets_xml_Drv94STt_js, mimeType: "application/javascript" },
  "assets/xsl-UGBeos0a.js": { content: fassets_xsl_UGBeos0a_js, mimeType: "application/javascript" },
  "assets/yaml-BbVzvNDQ.js": { content: fassets_yaml_BbVzvNDQ_js, mimeType: "application/javascript" },
  "assets/zenscript-De-g7R2L.js": { content: fassets_zenscript_De_g7R2L_js, mimeType: "application/javascript" },
  "assets/zig-Bzq_RqGF.js": { content: fassets_zig_Bzq_RqGF_js, mimeType: "application/javascript" },
  "assets/index-B-B5WRu6.css": { content: fassets_index_B_B5WRu6_css, mimeType: "text/css" },
  "assets/worker-UK_TsInR.js": { content: fassets_worker_UK_TsInR_js, mimeType: "application/javascript" },
  "index.html": { content: findex_html, mimeType: "text/html" }
};
